import type { MenuItem } from "./types"

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "1",
    name: "Hamburguesa Carne Asada",
    description: "Hamburguesa con carne asada, queso, lechuga, tomate y cebolla",
    price: 4.5,
    category: "main",
    image: "/h1.avif",
    available: true,
  },
  {
    id: "2",
    name: "Hamburguesa de Pollo",
    description: "Hamburguesa de pollo empanizado con lechuga, tomate y mayonesa",
    price: 2.5,
    category: "main",
    image: "/h2.webp",
    available: true,
  },
  {
    id: "3",
    name: "Hamburguesa Triple Queso",
    description: "Hamburguesa con tres tipos de queso derretido",
    price: 6.5,
    category: "main",
    image: "/h4.jpg",
    available: true,
  },
  {
    id: "4",
    name: "Hamburguesa Vegana",
    description: "Hamburguesa hecha con ingredientes 100% vegetales",
    price: 7.99,
    category: "main",
    image: "/h3.jpeg",
    available: true,
  },
  {
    id: "6",
    name: "Taco al Pastor",
    description: "Cerdo marinado con piña, cilantro y cebolla",
    price: 3.5,
    category: "main",
    image: "/taco-al-pastor-mexican-food.jpg",
    available: true,
  },
  {
    id: "5",
    name: "Burrito de Carne Asada",
    description: "Carne asada, frijoles, arroz, queso y guacamole",
    price: 8.99,
    category: "main",
    image: "/burrito-carne-asada-mexican.jpg",
    available: true,
  },
  {
    id: "7",
    name: "Cocteles",
    description: "Variedad de cocteles con y sin alcohol",
    price: 2.5,
    category: "drink",
    image: "/h10.webp",
    available: true,
  },
  {
    id: "8",
    name: "Churros",
    description: "Churros crujientes con azúcar y canela",
    price: 5.0,
    category: "dessert",
    image: "/churros-cinnamon-sugar.jpg",
    available: true,
  },
  {
    id: "9",
    name: "Flan",
    description: "Postre cremoso de caramelo",
    price: 4.5,
    category: "dessert",
    image: "/flan-caramel-dessert.jpg",
    available: true,
  },
  {
    id: "10",
    name: "Papas a la Francesa",
    description: "Papas fritas crujientes",
    price: 9.99,
    category: "side",
    image: "/h5.avif",
    available: true,
  },
  {
    id: "11",
    name: "Nuggets de Pollo",
    description: "Nuggets de pollo empanizados y fritos",
    price: 5.5,
    category: "side",
    image: "/h6.jpg",
    available: true,
  },
  {
    id: "12",
    name: "Gaseosas o Sodas",
    description: "Refrescos en lata de diferentes sabores",
    price: 2.5,
    category: "drink",
    image: "/h8.jpg",
    available: true,
  },
  {
    id: "13",
    name: "Helado de Oreo",
    description: "Helado cremoso con trozos de galleta Oreo",
    price: 3.0,
    category: "dessert",
    image: "/h11.jpeg",
    available: true,
  },
  {
    id: "14",
    name: "Cervezas en Botella",
    description: "Variedad de cervezas nacionales e importadas",
    price: 7.5,
    category: "drink",
    image: "/h9.jpg",
    available: true,
  },
  {
    id: "15",
    name: "Chicarrones de Cerdo",
    description: "Chicarrones crujientes con salsa picante",
    price: 4.0,
    category: "side",
    image: "/h7.avif",
    available: true,
  }
]
